Do not allow committing to master

diff --git a/src/git-hooks/pre-commit b/src/git-hooks/pre-commit
--- a/src/git-hooks/pre-commit
+++ b/src/git-hooks/pre-commit
@@ -1,2 +1,9 @@
 #!/bin/env sh
-flake8 --append-config=setup-dev.cfg src/astral.py
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
+
+#flake8 --append-config=setup-dev.cfg src/astral
